### ISSUE TITLE
Update of plugin in Eclipse failed

### ISSUE THREAD

**Issue by bartmark** [helospark/SparkTools#2]
Hi,

i wanted to update the plugin in Eclipse but got following Exception:
org.eclipse.equinox.p2.core.ProvisionException: Unable to read repository at ftp://helospark.com:799/eclipse_plugin/SparkBuilderGeneratorPlugin/content.xml.
	at org.eclipse.equinox.internal.p2.repository.CacheManager.createCache(CacheManager.java:243)
	at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.getLocalFile(SimpleMetadataRepositoryFactory.java:66)
	at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:88)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:116)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:386)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:193)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:453)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.doLoad(LoadMetadataRepositoryJob.java:117)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.runModal(LoadMetadataRepositoryJob.java:102)
	at org.eclipse.equinox.internal.p2.ui.sdk.PreloadingRepositoryHandler$2.runModal(PreloadingRepositoryHandler.java:83)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:177)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: ftp://helospark.com:799/eclipse_plugin/SparkBuilderGeneratorPlugin/content.xml
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(Unknown Source)
	at org.eclipse.ecf.provider.filetransfer.browse.URLFileSystemBrowser.runRequest(URLFileSystemBrowser.java:118)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	... 1 more

Best regards
Bartmark

**Comment by helospark** [comment]
Hi bartmark,

What Eclipse version are you using?
Are you not behind a firewall, that may block access to "unusual" outbound ports like 799? - Can you download the jar file [ftp://helospark.com:799/eclipse_plugin/SparkBuilderGeneratorPlugin/content.jar](ftp://helospark.com:799/eclipse_plugin/SparkBuilderGeneratorPlugin/content.jar) from your browser on the machine that you are trying to update the version on?
What does your browser says to the URI on the error message: [ftp://helospark.com:799/eclipse_plugin/SparkBuilderGeneratorPlugin/content.xml](ftp://helospark.com:799/eclipse_plugin/SparkBuilderGeneratorPlugin/content.xml). Is it just a your browser's error page or was the request intercepted by a proxy?

I was not able to reproduce it. It successfully updated on two different Eclipse versions. The content.xml file that the error message says is missing, but based on the Eclipse documentation it should look for content.jar in that case, which exists.
Also it seems to return HTTP response even though that is an FTP server. Status code 403 would mean permission denied, but I cannot see a response status code like that in the log files.

**Comment by bartmark** [comment]
Hi helospark,

It's Eclipse Neon and you're completely right, that it's not working too from the browser. And yes i am behind a proxy. 

Best regards
Mark

**Comment by bartmark** [comment]
Hi helospark,

due to i'm working for a bigger company, there are some restrictions on  accessing the internet. For e.g. only default ftp ports are accessible. You're using 799 as port and this is blocked for me. 
My Question now is, can you change your ftp port to a default port?
I think it would be good for the propagation / distribution of your plugin, when you're using a default ftp port, due to i'm not the only one, working for bigger companies with such restrictions ;-). 

best regards
bartmark

**Comment by helospark** [comment]
Hi bartmark,

My reasoning for using a nondefault port was to decrease the amount of continuous automatic scanning (vulnerability scanning, bruteforcing passwords, etc) my FTP server receives and I though that outbounds ports were rarely blocked by firewall.
But I have taken your advice and changed the port to 21 and will monitor the traffic (and the download number :).

**Comment by bartmark** [comment]
Perfect, now it works behind this proxy / firewall :-)

And for sure, your download numbers will increase ;-)
